In [ ]:
## What is a Python library? Why do we use Python libraries?

Python library is basically a collection of modules . Each library comprises multiple modules, which are smaller units containing functions, classes, and other building blocks. Think of modules as specific tools within the toolbox.

We use Python libraries for below reasons

1. Boost productivity
2. Improve code quality
3. Expand your capabilities

And many more other things

In [ ]:
## What is the difference between Numpy array and List?

The major differenes between Numpy Array and List are :

1. Numpy array can store the values of single data types(ex - All integrers or floats) while list can store values of multiple data types

2. Memory usage is more in list as compare to Numpy Array

3. Lists can be one-dimensional, while NumPy arrays can be multi-dimensional (matrices, etc.)

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

input_arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
input_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
input_arr.shape

(3, 4)

In [ ]:
input_arr.size

12

In [ ]:
input_arr.ndim

2

4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
input_arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

input_arr

input_arr[0]


array([1, 2, 3, 4])

4

5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
input_arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

input_arr

third_row = input_arr[2]
fourth_column = input_arr[:, 3]

print(third_row)
print(fourth_column)

[ 9 10 11 12]
[ 4  8 12]


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
input_arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
input_arr
odd_indexedelements = input_arr[:, 1::2]
odd_indexedelements



array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
## 7. How can you generate a random 3x3 matrix with values between 0 and 1

In [ ]:
import numpy as np

random_matrix = np.random.rand(3,3)
random_matrix

array([[0.30295233, 0.92598863, 0.68502261],
       [0.07560939, 0.60596768, 0.14208588],
       [0.50199109, 0.67959654, 0.95435997]])

In [ ]:
## Describe the difference between np.random.rand and np.random.randn?

The primary difference between np.random.rand and np.random.randn lies in the probability distribution they draw random numbers

np.random.rand draws samples from a uniform distribution in the range [0, 1). This means all values between 0 (exclusive) and 1 (exclusive) have an equal probability of being generated.

np.random.randn raws samples from a standard normal distribution. This is a bell-shaped curve centered at 0, where values closer to the center are more likely to be generated than those further away.




In [ ]:
arr1 = np.random.rand(3,4)

In [ ]:
arr1

array([[0.6277052 , 0.03775248, 0.9429245 , 0.81978731],
       [0.57550042, 0.40808551, 0.16275821, 0.18226851],
       [0.02633086, 0.39591883, 0.43028004, 0.60563549]])

In [ ]:
arr2 = np.random.randn(3,4)

In [ ]:
arr2


array([[-1.43699498, -1.70286655,  0.65122937, -1.8364467 ],
       [ 0.04824541, -0.38002314, -0.49231925,  1.23525483],
       [ 0.19990952,  0.86374233,  0.26152627,  0.86317445]])

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
input_arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
new_arr = np.expand_dims(input_arr, axis = 1)
new_arr

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [ ]:
new_arr.ndim

3

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
input_arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
new_arr = input_arr.T

In [ ]:
new_arr

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]



In [2]:
##  Index wise multiplication
import numpy as np
matrix_A2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
matrix_B2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

Mul_Index_Wise = matrix_A2 * matrix_B2
Mul_Index_Wise


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [3]:
## Matrix Multiplication

In [6]:
Mul_matrix = np.matmul(matrix_A2.T, matrix_B2)
Mul_matrix

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

In [9]:
print(matrix_A2.shape)
print(matrix_B2.shape)

(3, 4)
(3, 4)


In [10]:
##  Add both the matrics

In [11]:
Add_mat = matrix_A2 + matrix_B2
Add_mat

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [12]:
## Subtract Matrix B from A

Output = matrix_B2 - matrix_B2
Output

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
## Divide Matrix B By A

In [14]:
Div_Result = matrix_B2 / matrix_B2
Div_Result

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## Which function in Numpy can be used to swap the byte order of an array?


The byteswap() function in NumPy is used to swap the byte order of an array.

It's like switching between big-endian (storing most significant byte first) and little-endian (storing least significant byte first) representations.

In [ ]:
## What does the np.reshape function do, and how is it used?

It reorganizes the elements of an array into a new shape without modifying the data itself.
It's like rearranging the same items in a box into different rows and columns.

In [18]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
new_array = arr.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# What is broadcasting in Numpy?



In NumPy, broadcasting refers to a powerful feature that allows arrays of different shapes to be used in mathematical operations together. It essentially replicates the smaller array across the larger array to make their dimensions compatible for element-wise calculations.

In [21]:
# For Example
arr1 = np.array([1,2,3,4,5,6])
arr2 = 5
res = arr1 + arr2
res


array([ 6,  7,  8,  9, 10, 11])

In [28]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,4])
res = arr1 @ arr2
res

array([ 9, 19])